# 250-SoC PL DDR4 pinout (DDR4_2400_250SP, 72-bit = 64 data + 8 ECC, x16 components).
# For the DDR4 (MIG) IP: interface name ddr4_rtl_0, system clock diff_clock_rtl_1 (J19).
# NOTE: diff_clock_rtl_0 (AH10) and reset_rtl_0 (AM16) here are the HOST PCIe ref clock / reset and already
# exist in fpga-nvme-driver.xdc as host_ref_clk_p[0] / host_rstn -- do NOT duplicate; only the ddr4_rtl_0_*
# pins and diff_clock_rtl_1 below are added for the DDR4 controller.

# ---- DDR4 system clock ----
set_property PACKAGE_PIN J19 [get_ports diff_clock_rtl_1_clk_p]

# ---- address (17) ----
set_property PACKAGE_PIN J17 [get_ports {ddr4_rtl_0_adr[16]}]
set_property PACKAGE_PIN M16 [get_ports {ddr4_rtl_0_adr[15]}]
set_property PACKAGE_PIN K18 [get_ports {ddr4_rtl_0_adr[14]}]
set_property PACKAGE_PIN P20 [get_ports {ddr4_rtl_0_adr[13]}]
set_property PACKAGE_PIN G19 [get_ports {ddr4_rtl_0_adr[12]}]
set_property PACKAGE_PIN R20 [get_ports {ddr4_rtl_0_adr[11]}]
set_property PACKAGE_PIN G16 [get_ports {ddr4_rtl_0_adr[10]}]
set_property PACKAGE_PIN N17 [get_ports {ddr4_rtl_0_adr[9]}]
set_property PACKAGE_PIN P19 [get_ports {ddr4_rtl_0_adr[8]}]
set_property PACKAGE_PIN N20 [get_ports {ddr4_rtl_0_adr[7]}]
set_property PACKAGE_PIN N19 [get_ports {ddr4_rtl_0_adr[6]}]
set_property PACKAGE_PIN M19 [get_ports {ddr4_rtl_0_adr[5]}]
set_property PACKAGE_PIN H16 [get_ports {ddr4_rtl_0_adr[4]}]
set_property PACKAGE_PIN G18 [get_ports {ddr4_rtl_0_adr[3]}]
set_property PACKAGE_PIN R18 [get_ports {ddr4_rtl_0_adr[2]}]
set_property PACKAGE_PIN H17 [get_ports {ddr4_rtl_0_adr[1]}]
set_property PACKAGE_PIN N16 [get_ports {ddr4_rtl_0_adr[0]}]

# ---- data mask (9) ----
set_property PACKAGE_PIN R27 [get_ports {ddr4_rtl_0_dm_n[8]}]
set_property PACKAGE_PIN L25 [get_ports {ddr4_rtl_0_dm_n[7]}]
set_property PACKAGE_PIN H25 [get_ports {ddr4_rtl_0_dm_n[6]}]
set_property PACKAGE_PIN C25 [get_ports {ddr4_rtl_0_dm_n[5]}]
set_property PACKAGE_PIN D22 [get_ports {ddr4_rtl_0_dm_n[4]}]
set_property PACKAGE_PIN D18 [get_ports {ddr4_rtl_0_dm_n[3]}]
set_property PACKAGE_PIN H20 [get_ports {ddr4_rtl_0_dm_n[2]}]
set_property PACKAGE_PIN R24 [get_ports {ddr4_rtl_0_dm_n[1]}]
set_property PACKAGE_PIN M21 [get_ports {ddr4_rtl_0_dm_n[0]}]

# ---- data (72) ----
set_property PACKAGE_PIN P27 [get_ports {ddr4_rtl_0_dq[71]}]
set_property PACKAGE_PIN N27 [get_ports {ddr4_rtl_0_dq[70]}]
set_property PACKAGE_PIN P28 [get_ports {ddr4_rtl_0_dq[69]}]
set_property PACKAGE_PIN N26 [get_ports {ddr4_rtl_0_dq[68]}]
set_property PACKAGE_PIN P26 [get_ports {ddr4_rtl_0_dq[67]}]
set_property PACKAGE_PIN M28 [get_ports {ddr4_rtl_0_dq[66]}]
set_property PACKAGE_PIN R26 [get_ports {ddr4_rtl_0_dq[65]}]
set_property PACKAGE_PIN M27 [get_ports {ddr4_rtl_0_dq[64]}]
set_property PACKAGE_PIN K25 [get_ports {ddr4_rtl_0_dq[63]}]
set_property PACKAGE_PIN G28 [get_ports {ddr4_rtl_0_dq[62]}]
set_property PACKAGE_PIN K27 [get_ports {ddr4_rtl_0_dq[61]}]
set_property PACKAGE_PIN H26 [get_ports {ddr4_rtl_0_dq[60]}]
set_property PACKAGE_PIN K26 [get_ports {ddr4_rtl_0_dq[59]}]
set_property PACKAGE_PIN H27 [get_ports {ddr4_rtl_0_dq[58]}]
set_property PACKAGE_PIN K28 [get_ports {ddr4_rtl_0_dq[57]}]
set_property PACKAGE_PIN J25 [get_ports {ddr4_rtl_0_dq[56]}]
set_property PACKAGE_PIN F25 [get_ports {ddr4_rtl_0_dq[55]}]
set_property PACKAGE_PIN E25 [get_ports {ddr4_rtl_0_dq[54]}]
set_property PACKAGE_PIN F28 [get_ports {ddr4_rtl_0_dq[53]}]
set_property PACKAGE_PIN D27 [get_ports {ddr4_rtl_0_dq[52]}]
set_property PACKAGE_PIN F26 [get_ports {ddr4_rtl_0_dq[51]}]
set_property PACKAGE_PIN E26 [get_ports {ddr4_rtl_0_dq[50]}]
set_property PACKAGE_PIN G27 [get_ports {ddr4_rtl_0_dq[49]}]
set_property PACKAGE_PIN D28 [get_ports {ddr4_rtl_0_dq[48]}]
set_property PACKAGE_PIN B26 [get_ports {ddr4_rtl_0_dq[47]}]
set_property PACKAGE_PIN A25 [get_ports {ddr4_rtl_0_dq[46]}]
set_property PACKAGE_PIN C27 [get_ports {ddr4_rtl_0_dq[45]}]
set_property PACKAGE_PIN C24 [get_ports {ddr4_rtl_0_dq[44]}]
set_property PACKAGE_PIN A26 [get_ports {ddr4_rtl_0_dq[43]}]
set_property PACKAGE_PIN A24 [get_ports {ddr4_rtl_0_dq[42]}]
set_property PACKAGE_PIN B28 [get_ports {ddr4_rtl_0_dq[41]}]
set_property PACKAGE_PIN B24 [get_ports {ddr4_rtl_0_dq[40]}]
set_property PACKAGE_PIN B23 [get_ports {ddr4_rtl_0_dq[39]}]
set_property PACKAGE_PIN B22 [get_ports {ddr4_rtl_0_dq[38]}]
set_property PACKAGE_PIN C22 [get_ports {ddr4_rtl_0_dq[37]}]
set_property PACKAGE_PIN A23 [get_ports {ddr4_rtl_0_dq[36]}]
set_property PACKAGE_PIN C21 [get_ports {ddr4_rtl_0_dq[35]}]
set_property PACKAGE_PIN A20 [get_ports {ddr4_rtl_0_dq[34]}]
set_property PACKAGE_PIN D20 [get_ports {ddr4_rtl_0_dq[33]}]
set_property PACKAGE_PIN A21 [get_ports {ddr4_rtl_0_dq[32]}]
set_property PACKAGE_PIN A19 [get_ports {ddr4_rtl_0_dq[31]}]
set_property PACKAGE_PIN C17 [get_ports {ddr4_rtl_0_dq[30]}]
set_property PACKAGE_PIN B19 [get_ports {ddr4_rtl_0_dq[29]}]
set_property PACKAGE_PIN B16 [get_ports {ddr4_rtl_0_dq[28]}]
set_property PACKAGE_PIN A18 [get_ports {ddr4_rtl_0_dq[27]}]
set_property PACKAGE_PIN A16 [get_ports {ddr4_rtl_0_dq[26]}]
set_property PACKAGE_PIN C19 [get_ports {ddr4_rtl_0_dq[25]}]
set_property PACKAGE_PIN C16 [get_ports {ddr4_rtl_0_dq[24]}]
set_property PACKAGE_PIN G22 [get_ports {ddr4_rtl_0_dq[23]}]
set_property PACKAGE_PIN G21 [get_ports {ddr4_rtl_0_dq[22]}]
set_property PACKAGE_PIN G23 [get_ports {ddr4_rtl_0_dq[21]}]
set_property PACKAGE_PIN F21 [get_ports {ddr4_rtl_0_dq[20]}]
set_property PACKAGE_PIN G24 [get_ports {ddr4_rtl_0_dq[19]}]
set_property PACKAGE_PIN E22 [get_ports {ddr4_rtl_0_dq[18]}]
set_property PACKAGE_PIN E23 [get_ports {ddr4_rtl_0_dq[17]}]
set_property PACKAGE_PIN F20 [get_ports {ddr4_rtl_0_dq[16]}]
set_property PACKAGE_PIN M24 [get_ports {ddr4_rtl_0_dq[15]}]
set_property PACKAGE_PIN P22 [get_ports {ddr4_rtl_0_dq[14]}]
set_property PACKAGE_PIN M23 [get_ports {ddr4_rtl_0_dq[13]}]
set_property PACKAGE_PIN R23 [get_ports {ddr4_rtl_0_dq[12]}]
set_property PACKAGE_PIN N24 [get_ports {ddr4_rtl_0_dq[11]}]
set_property PACKAGE_PIN P23 [get_ports {ddr4_rtl_0_dq[10]}]
set_property PACKAGE_PIN M22 [get_ports {ddr4_rtl_0_dq[9]}]
set_property PACKAGE_PIN R22 [get_ports {ddr4_rtl_0_dq[8]}]
set_property PACKAGE_PIN J24 [get_ports {ddr4_rtl_0_dq[7]}]
set_property PACKAGE_PIN H24 [get_ports {ddr4_rtl_0_dq[6]}]
set_property PACKAGE_PIN K23 [get_ports {ddr4_rtl_0_dq[5]}]
set_property PACKAGE_PIN K22 [get_ports {ddr4_rtl_0_dq[4]}]
set_property PACKAGE_PIN J23 [get_ports {ddr4_rtl_0_dq[3]}]
set_property PACKAGE_PIN J22 [get_ports {ddr4_rtl_0_dq[2]}]
set_property PACKAGE_PIN H22 [get_ports {ddr4_rtl_0_dq[1]}]
set_property PACKAGE_PIN K21 [get_ports {ddr4_rtl_0_dq[0]}]

# ---- bank / control ----
set_property PACKAGE_PIN L19 [get_ports {ddr4_rtl_0_ba[1]}]
set_property PACKAGE_PIN L20 [get_ports {ddr4_rtl_0_ba[0]}]
set_property PACKAGE_PIN L16 [get_ports {ddr4_rtl_0_cke[0]}]
set_property PACKAGE_PIN F19 [get_ports {ddr4_rtl_0_cs_n[0]}]
set_property PACKAGE_PIN E17 [get_ports {ddr4_rtl_0_odt[0]}]
set_property PACKAGE_PIN L18 [get_ports {ddr4_rtl_0_bg[0]}]

# ---- data strobes (9 diff pairs) ----
set_property PACKAGE_PIN P25 [get_ports {ddr4_rtl_0_dqs_t[8]}]
set_property PACKAGE_PIN N25 [get_ports {ddr4_rtl_0_dqs_c[8]}]
set_property PACKAGE_PIN J27 [get_ports {ddr4_rtl_0_dqs_t[7]}]
set_property PACKAGE_PIN J28 [get_ports {ddr4_rtl_0_dqs_c[7]}]
set_property PACKAGE_PIN E27 [get_ports {ddr4_rtl_0_dqs_t[6]}]
set_property PACKAGE_PIN E28 [get_ports {ddr4_rtl_0_dqs_c[6]}]
set_property PACKAGE_PIN B27 [get_ports {ddr4_rtl_0_dqs_t[5]}]
set_property PACKAGE_PIN A28 [get_ports {ddr4_rtl_0_dqs_c[5]}]
set_property PACKAGE_PIN C20 [get_ports {ddr4_rtl_0_dqs_t[4]}]
set_property PACKAGE_PIN B21 [get_ports {ddr4_rtl_0_dqs_c[4]}]
set_property PACKAGE_PIN B18 [get_ports {ddr4_rtl_0_dqs_t[3]}]
set_property PACKAGE_PIN B17 [get_ports {ddr4_rtl_0_dqs_c[3]}]
set_property PACKAGE_PIN F23 [get_ports {ddr4_rtl_0_dqs_t[2]}]
set_property PACKAGE_PIN F24 [get_ports {ddr4_rtl_0_dqs_c[2]}]
set_property PACKAGE_PIN N21 [get_ports {ddr4_rtl_0_dqs_t[1]}]
set_property PACKAGE_PIN N22 [get_ports {ddr4_rtl_0_dqs_c[1]}]
set_property PACKAGE_PIN K20 [get_ports {ddr4_rtl_0_dqs_t[0]}]
set_property PACKAGE_PIN J20 [get_ports {ddr4_rtl_0_dqs_c[0]}]

# ---- act / ck / reset ----
set_property PACKAGE_PIN F16 [get_ports ddr4_rtl_0_act_n]
set_property PACKAGE_PIN K17 [get_ports {ddr4_rtl_0_ck_t[0]}]
set_property PACKAGE_PIN G17 [get_ports ddr4_rtl_0_reset_n]
