#include <cuda_runtime.h>
#include <cstdio>

#define GEN_CASE(X) \
  do { \
    char buf[999]; \
    sprintf(buf, "case " #X ": return \"%s\";\n", cudaGetErrorString(X)); \
    buf[5] = 's'; \
    printf("%s", buf); \
  } while (0)

int main() {
  GEN_CASE(cudaSuccess);
  GEN_CASE(cudaErrorInvalidValue);
  GEN_CASE(cudaErrorMemoryAllocation);
  GEN_CASE(cudaErrorInitializationError);
  GEN_CASE(cudaErrorCudartUnloading);
  GEN_CASE(cudaErrorProfilerDisabled);
  GEN_CASE(cudaErrorProfilerNotInitialized);
  GEN_CASE(cudaErrorProfilerAlreadyStarted);
  GEN_CASE(cudaErrorProfilerAlreadyStopped);
  GEN_CASE(cudaErrorInvalidConfiguration);
  GEN_CASE(cudaErrorInvalidPitchValue);
  GEN_CASE(cudaErrorInvalidSymbol);
  GEN_CASE(cudaErrorInvalidHostPointer);
  GEN_CASE(cudaErrorInvalidDevicePointer);
  GEN_CASE(cudaErrorInvalidTexture);
  GEN_CASE(cudaErrorInvalidTextureBinding);
  GEN_CASE(cudaErrorInvalidChannelDescriptor);
  GEN_CASE(cudaErrorInvalidMemcpyDirection);
  GEN_CASE(cudaErrorAddressOfConstant);
  GEN_CASE(cudaErrorTextureFetchFailed);
  GEN_CASE(cudaErrorTextureNotBound);
  GEN_CASE(cudaErrorSynchronizationError);
  GEN_CASE(cudaErrorInvalidFilterSetting);
  GEN_CASE(cudaErrorInvalidNormSetting);
  GEN_CASE(cudaErrorMixedDeviceExecution);
  GEN_CASE(cudaErrorNotYetImplemented);
  GEN_CASE(cudaErrorMemoryValueTooLarge);
  GEN_CASE(cudaErrorStubLibrary);
  GEN_CASE(cudaErrorInsufficientDriver);
  GEN_CASE(cudaErrorCallRequiresNewerDriver);
  GEN_CASE(cudaErrorInvalidSurface);
  GEN_CASE(cudaErrorDuplicateVariableName);
  GEN_CASE(cudaErrorDuplicateTextureName);
  GEN_CASE(cudaErrorDuplicateSurfaceName);
  GEN_CASE(cudaErrorDevicesUnavailable);
  GEN_CASE(cudaErrorIncompatibleDriverContext);
  GEN_CASE(cudaErrorMissingConfiguration);
  GEN_CASE(cudaErrorPriorLaunchFailure);
  GEN_CASE(cudaErrorLaunchMaxDepthExceeded);
  GEN_CASE(cudaErrorLaunchFileScopedTex);
  GEN_CASE(cudaErrorLaunchFileScopedSurf);
  GEN_CASE(cudaErrorSyncDepthExceeded);
  GEN_CASE(cudaErrorLaunchPendingCountExceeded);
  GEN_CASE(cudaErrorInvalidDeviceFunction);
  GEN_CASE(cudaErrorNoDevice);
  GEN_CASE(cudaErrorInvalidDevice);
  GEN_CASE(cudaErrorDeviceNotLicensed);
  GEN_CASE(cudaErrorSoftwareValidityNotEstablished);
  GEN_CASE(cudaErrorStartupFailure);
  GEN_CASE(cudaErrorInvalidKernelImage);
  GEN_CASE(cudaErrorDeviceUninitialized);
  GEN_CASE(cudaErrorMapBufferObjectFailed);
  GEN_CASE(cudaErrorUnmapBufferObjectFailed);
  GEN_CASE(cudaErrorArrayIsMapped);
  GEN_CASE(cudaErrorAlreadyMapped);
  GEN_CASE(cudaErrorNoKernelImageForDevice);
  GEN_CASE(cudaErrorAlreadyAcquired);
  GEN_CASE(cudaErrorNotMapped);
  GEN_CASE(cudaErrorNotMappedAsArray);
  GEN_CASE(cudaErrorNotMappedAsPointer);
  GEN_CASE(cudaErrorECCUncorrectable);
  GEN_CASE(cudaErrorUnsupportedLimit);
  GEN_CASE(cudaErrorDeviceAlreadyInUse);
  GEN_CASE(cudaErrorPeerAccessUnsupported);
  GEN_CASE(cudaErrorInvalidPtx);
  GEN_CASE(cudaErrorInvalidGraphicsContext);
  GEN_CASE(cudaErrorNvlinkUncorrectable);
  GEN_CASE(cudaErrorJitCompilerNotFound);
  GEN_CASE(cudaErrorUnsupportedPtxVersion);
  GEN_CASE(cudaErrorJitCompilationDisabled);
  GEN_CASE(cudaErrorUnsupportedExecAffinity);
  GEN_CASE(cudaErrorInvalidSource);
  GEN_CASE(cudaErrorFileNotFound);
  GEN_CASE(cudaErrorSharedObjectSymbolNotFound);
  GEN_CASE(cudaErrorSharedObjectInitFailed);
  GEN_CASE(cudaErrorOperatingSystem);
  GEN_CASE(cudaErrorInvalidResourceHandle);
  GEN_CASE(cudaErrorIllegalState);
  GEN_CASE(cudaErrorSymbolNotFound);
  GEN_CASE(cudaErrorNotReady);
  GEN_CASE(cudaErrorIllegalAddress);
  GEN_CASE(cudaErrorLaunchOutOfResources);
  GEN_CASE(cudaErrorLaunchTimeout);
  GEN_CASE(cudaErrorLaunchIncompatibleTexturing);
  GEN_CASE(cudaErrorPeerAccessAlreadyEnabled);
  GEN_CASE(cudaErrorPeerAccessNotEnabled);
  GEN_CASE(cudaErrorSetOnActiveProcess);
  GEN_CASE(cudaErrorContextIsDestroyed);
  GEN_CASE(cudaErrorAssert);
  GEN_CASE(cudaErrorTooManyPeers);
  GEN_CASE(cudaErrorHostMemoryAlreadyRegistered);
  GEN_CASE(cudaErrorHostMemoryNotRegistered);
  GEN_CASE(cudaErrorHardwareStackError);
  GEN_CASE(cudaErrorIllegalInstruction);
  GEN_CASE(cudaErrorMisalignedAddress);
  GEN_CASE(cudaErrorInvalidAddressSpace);
  GEN_CASE(cudaErrorInvalidPc);
  GEN_CASE(cudaErrorLaunchFailure);
  GEN_CASE(cudaErrorCooperativeLaunchTooLarge);
  GEN_CASE(cudaErrorNotPermitted);
  GEN_CASE(cudaErrorNotSupported);
  GEN_CASE(cudaErrorSystemNotReady);
  GEN_CASE(cudaErrorSystemDriverMismatch);
  GEN_CASE(cudaErrorCompatNotSupportedOnDevice);
  GEN_CASE(cudaErrorMpsConnectionFailed);
  GEN_CASE(cudaErrorMpsRpcFailure);
  GEN_CASE(cudaErrorMpsServerNotReady);
  GEN_CASE(cudaErrorMpsMaxClientsReached);
  GEN_CASE(cudaErrorMpsMaxConnectionsReached);
  GEN_CASE(cudaErrorMpsClientTerminated);
  GEN_CASE(cudaErrorStreamCaptureUnsupported);
  GEN_CASE(cudaErrorStreamCaptureInvalidated);
  GEN_CASE(cudaErrorStreamCaptureMerge);
  GEN_CASE(cudaErrorStreamCaptureUnmatched);
  GEN_CASE(cudaErrorStreamCaptureUnjoined);
  GEN_CASE(cudaErrorStreamCaptureIsolation);
  GEN_CASE(cudaErrorStreamCaptureImplicit);
  GEN_CASE(cudaErrorCapturedEvent);
  GEN_CASE(cudaErrorStreamCaptureWrongThread);
  GEN_CASE(cudaErrorTimeout);
  GEN_CASE(cudaErrorGraphExecUpdateFailure);
  GEN_CASE(cudaErrorExternalDevice);
  GEN_CASE(cudaErrorInvalidClusterSize);
  GEN_CASE(cudaErrorUnknown);
  GEN_CASE(cudaErrorApiFailureBase);
  return 0;
}