#include <cuda.h>
#include <cstdio>
#include <cstdlib>
#include <cstring>

#define GEN_NAME(X) \
  do { \
    const char *name_; \
    cuGetErrorName(X, &name_); \
    char* name = strdup(name_); \
    name[0] = 'S'; \
    printf("case %s: *pStr = \"%s\"; break;\n", name, name); \
    free(name); \
  } while (0)

#define GEN_STRING(X) \
  do { \
    const char *name_, *str; \
    cuGetErrorName(X, &name_); \
    cuGetErrorString(X, &str); \
    char* name = strdup(name_); \
    name[0] = 'S'; \
    printf("case %s: *pStr = \"%s\"; break;\n", name, str); \
    free(name); \
  } while (0)

int main() {
  GEN_NAME(CUDA_SUCCESS);
  GEN_NAME(CUDA_ERROR_INVALID_VALUE);
  GEN_NAME(CUDA_ERROR_OUT_OF_MEMORY);
  GEN_NAME(CUDA_ERROR_NOT_INITIALIZED);
  GEN_NAME(CUDA_ERROR_DEINITIALIZED);
  GEN_NAME(CUDA_ERROR_PROFILER_DISABLED);
  GEN_NAME(CUDA_ERROR_PROFILER_NOT_INITIALIZED);
  GEN_NAME(CUDA_ERROR_PROFILER_ALREADY_STARTED);
  GEN_NAME(CUDA_ERROR_PROFILER_ALREADY_STOPPED);
  GEN_NAME(CUDA_ERROR_STUB_LIBRARY);
  GEN_NAME(CUDA_ERROR_DEVICE_UNAVAILABLE);
  GEN_NAME(CUDA_ERROR_NO_DEVICE);
  GEN_NAME(CUDA_ERROR_INVALID_DEVICE);
  GEN_NAME(CUDA_ERROR_DEVICE_NOT_LICENSED);
  GEN_NAME(CUDA_ERROR_INVALID_IMAGE);
  GEN_NAME(CUDA_ERROR_INVALID_CONTEXT);
  GEN_NAME(CUDA_ERROR_CONTEXT_ALREADY_CURRENT);
  GEN_NAME(CUDA_ERROR_MAP_FAILED);
  GEN_NAME(CUDA_ERROR_UNMAP_FAILED);
  GEN_NAME(CUDA_ERROR_ARRAY_IS_MAPPED);
  GEN_NAME(CUDA_ERROR_ALREADY_MAPPED);
  GEN_NAME(CUDA_ERROR_NO_BINARY_FOR_GPU);
  GEN_NAME(CUDA_ERROR_ALREADY_ACQUIRED);
  GEN_NAME(CUDA_ERROR_NOT_MAPPED);
  GEN_NAME(CUDA_ERROR_NOT_MAPPED_AS_ARRAY);
  GEN_NAME(CUDA_ERROR_NOT_MAPPED_AS_POINTER);
  GEN_NAME(CUDA_ERROR_ECC_UNCORRECTABLE);
  GEN_NAME(CUDA_ERROR_UNSUPPORTED_LIMIT);
  GEN_NAME(CUDA_ERROR_CONTEXT_ALREADY_IN_USE);
  GEN_NAME(CUDA_ERROR_PEER_ACCESS_UNSUPPORTED);
  GEN_NAME(CUDA_ERROR_INVALID_PTX);
  GEN_NAME(CUDA_ERROR_INVALID_GRAPHICS_CONTEXT);
  GEN_NAME(CUDA_ERROR_NVLINK_UNCORRECTABLE);
  GEN_NAME(CUDA_ERROR_JIT_COMPILER_NOT_FOUND);
  GEN_NAME(CUDA_ERROR_UNSUPPORTED_PTX_VERSION);
  GEN_NAME(CUDA_ERROR_JIT_COMPILATION_DISABLED);
  GEN_NAME(CUDA_ERROR_UNSUPPORTED_EXEC_AFFINITY);
  GEN_NAME(CUDA_ERROR_INVALID_SOURCE);
  GEN_NAME(CUDA_ERROR_FILE_NOT_FOUND);
  GEN_NAME(CUDA_ERROR_SHARED_OBJECT_SYMBOL_NOT_FOUND);
  GEN_NAME(CUDA_ERROR_SHARED_OBJECT_INIT_FAILED);
  GEN_NAME(CUDA_ERROR_OPERATING_SYSTEM);
  GEN_NAME(CUDA_ERROR_INVALID_HANDLE);
  GEN_NAME(CUDA_ERROR_ILLEGAL_STATE);
  GEN_NAME(CUDA_ERROR_NOT_FOUND);
  GEN_NAME(CUDA_ERROR_NOT_READY);
  GEN_NAME(CUDA_ERROR_ILLEGAL_ADDRESS);
  GEN_NAME(CUDA_ERROR_LAUNCH_OUT_OF_RESOURCES);
  GEN_NAME(CUDA_ERROR_LAUNCH_TIMEOUT);
  GEN_NAME(CUDA_ERROR_LAUNCH_INCOMPATIBLE_TEXTURING);
  GEN_NAME(CUDA_ERROR_PEER_ACCESS_ALREADY_ENABLED);
  GEN_NAME(CUDA_ERROR_PEER_ACCESS_NOT_ENABLED);
  GEN_NAME(CUDA_ERROR_PRIMARY_CONTEXT_ACTIVE);
  GEN_NAME(CUDA_ERROR_CONTEXT_IS_DESTROYED);
  GEN_NAME(CUDA_ERROR_ASSERT);
  GEN_NAME(CUDA_ERROR_TOO_MANY_PEERS);
  GEN_NAME(CUDA_ERROR_HOST_MEMORY_ALREADY_REGISTERED);
  GEN_NAME(CUDA_ERROR_HOST_MEMORY_NOT_REGISTERED);
  GEN_NAME(CUDA_ERROR_HARDWARE_STACK_ERROR);
  GEN_NAME(CUDA_ERROR_ILLEGAL_INSTRUCTION);
  GEN_NAME(CUDA_ERROR_MISALIGNED_ADDRESS);
  GEN_NAME(CUDA_ERROR_INVALID_ADDRESS_SPACE);
  GEN_NAME(CUDA_ERROR_INVALID_PC);
  GEN_NAME(CUDA_ERROR_LAUNCH_FAILED);
  GEN_NAME(CUDA_ERROR_COOPERATIVE_LAUNCH_TOO_LARGE);
  GEN_NAME(CUDA_ERROR_NOT_PERMITTED);
  GEN_NAME(CUDA_ERROR_NOT_SUPPORTED);
  GEN_NAME(CUDA_ERROR_SYSTEM_NOT_READY);
  GEN_NAME(CUDA_ERROR_SYSTEM_DRIVER_MISMATCH);
  GEN_NAME(CUDA_ERROR_COMPAT_NOT_SUPPORTED_ON_DEVICE);
  GEN_NAME(CUDA_ERROR_MPS_CONNECTION_FAILED);
  GEN_NAME(CUDA_ERROR_MPS_RPC_FAILURE);
  GEN_NAME(CUDA_ERROR_MPS_SERVER_NOT_READY);
  GEN_NAME(CUDA_ERROR_MPS_MAX_CLIENTS_REACHED);
  GEN_NAME(CUDA_ERROR_MPS_MAX_CONNECTIONS_REACHED);
  GEN_NAME(CUDA_ERROR_MPS_CLIENT_TERMINATED);
  GEN_NAME(CUDA_ERROR_STREAM_CAPTURE_UNSUPPORTED);
  GEN_NAME(CUDA_ERROR_STREAM_CAPTURE_INVALIDATED);
  GEN_NAME(CUDA_ERROR_STREAM_CAPTURE_MERGE);
  GEN_NAME(CUDA_ERROR_STREAM_CAPTURE_UNMATCHED);
  GEN_NAME(CUDA_ERROR_STREAM_CAPTURE_UNJOINED);
  GEN_NAME(CUDA_ERROR_STREAM_CAPTURE_ISOLATION);
  GEN_NAME(CUDA_ERROR_STREAM_CAPTURE_IMPLICIT);
  GEN_NAME(CUDA_ERROR_CAPTURED_EVENT);
  GEN_NAME(CUDA_ERROR_STREAM_CAPTURE_WRONG_THREAD);
  GEN_NAME(CUDA_ERROR_TIMEOUT);
  GEN_NAME(CUDA_ERROR_GRAPH_EXEC_UPDATE_FAILURE);
  GEN_NAME(CUDA_ERROR_EXTERNAL_DEVICE);
  GEN_NAME(CUDA_ERROR_INVALID_CLUSTER_SIZE);
  GEN_NAME(CUDA_ERROR_UNKNOWN);

  GEN_STRING(CUDA_SUCCESS);
  GEN_STRING(CUDA_ERROR_INVALID_VALUE);
  GEN_STRING(CUDA_ERROR_OUT_OF_MEMORY);
  GEN_STRING(CUDA_ERROR_NOT_INITIALIZED);
  GEN_STRING(CUDA_ERROR_DEINITIALIZED);
  GEN_STRING(CUDA_ERROR_PROFILER_DISABLED);
  GEN_STRING(CUDA_ERROR_PROFILER_NOT_INITIALIZED);
  GEN_STRING(CUDA_ERROR_PROFILER_ALREADY_STARTED);
  GEN_STRING(CUDA_ERROR_PROFILER_ALREADY_STOPPED);
  GEN_STRING(CUDA_ERROR_STUB_LIBRARY);
  GEN_STRING(CUDA_ERROR_DEVICE_UNAVAILABLE);
  GEN_STRING(CUDA_ERROR_NO_DEVICE);
  GEN_STRING(CUDA_ERROR_INVALID_DEVICE);
  GEN_STRING(CUDA_ERROR_DEVICE_NOT_LICENSED);
  GEN_STRING(CUDA_ERROR_INVALID_IMAGE);
  GEN_STRING(CUDA_ERROR_INVALID_CONTEXT);
  GEN_STRING(CUDA_ERROR_CONTEXT_ALREADY_CURRENT);
  GEN_STRING(CUDA_ERROR_MAP_FAILED);
  GEN_STRING(CUDA_ERROR_UNMAP_FAILED);
  GEN_STRING(CUDA_ERROR_ARRAY_IS_MAPPED);
  GEN_STRING(CUDA_ERROR_ALREADY_MAPPED);
  GEN_STRING(CUDA_ERROR_NO_BINARY_FOR_GPU);
  GEN_STRING(CUDA_ERROR_ALREADY_ACQUIRED);
  GEN_STRING(CUDA_ERROR_NOT_MAPPED);
  GEN_STRING(CUDA_ERROR_NOT_MAPPED_AS_ARRAY);
  GEN_STRING(CUDA_ERROR_NOT_MAPPED_AS_POINTER);
  GEN_STRING(CUDA_ERROR_ECC_UNCORRECTABLE);
  GEN_STRING(CUDA_ERROR_UNSUPPORTED_LIMIT);
  GEN_STRING(CUDA_ERROR_CONTEXT_ALREADY_IN_USE);
  GEN_STRING(CUDA_ERROR_PEER_ACCESS_UNSUPPORTED);
  GEN_STRING(CUDA_ERROR_INVALID_PTX);
  GEN_STRING(CUDA_ERROR_INVALID_GRAPHICS_CONTEXT);
  GEN_STRING(CUDA_ERROR_NVLINK_UNCORRECTABLE);
  GEN_STRING(CUDA_ERROR_JIT_COMPILER_NOT_FOUND);
  GEN_STRING(CUDA_ERROR_UNSUPPORTED_PTX_VERSION);
  GEN_STRING(CUDA_ERROR_JIT_COMPILATION_DISABLED);
  GEN_STRING(CUDA_ERROR_UNSUPPORTED_EXEC_AFFINITY);
  GEN_STRING(CUDA_ERROR_INVALID_SOURCE);
  GEN_STRING(CUDA_ERROR_FILE_NOT_FOUND);
  GEN_STRING(CUDA_ERROR_SHARED_OBJECT_SYMBOL_NOT_FOUND);
  GEN_STRING(CUDA_ERROR_SHARED_OBJECT_INIT_FAILED);
  GEN_STRING(CUDA_ERROR_OPERATING_SYSTEM);
  GEN_STRING(CUDA_ERROR_INVALID_HANDLE);
  GEN_STRING(CUDA_ERROR_ILLEGAL_STATE);
  GEN_STRING(CUDA_ERROR_NOT_FOUND);
  GEN_STRING(CUDA_ERROR_NOT_READY);
  GEN_STRING(CUDA_ERROR_ILLEGAL_ADDRESS);
  GEN_STRING(CUDA_ERROR_LAUNCH_OUT_OF_RESOURCES);
  GEN_STRING(CUDA_ERROR_LAUNCH_TIMEOUT);
  GEN_STRING(CUDA_ERROR_LAUNCH_INCOMPATIBLE_TEXTURING);
  GEN_STRING(CUDA_ERROR_PEER_ACCESS_ALREADY_ENABLED);
  GEN_STRING(CUDA_ERROR_PEER_ACCESS_NOT_ENABLED);
  GEN_STRING(CUDA_ERROR_PRIMARY_CONTEXT_ACTIVE);
  GEN_STRING(CUDA_ERROR_CONTEXT_IS_DESTROYED);
  GEN_STRING(CUDA_ERROR_ASSERT);
  GEN_STRING(CUDA_ERROR_TOO_MANY_PEERS);
  GEN_STRING(CUDA_ERROR_HOST_MEMORY_ALREADY_REGISTERED);
  GEN_STRING(CUDA_ERROR_HOST_MEMORY_NOT_REGISTERED);
  GEN_STRING(CUDA_ERROR_HARDWARE_STACK_ERROR);
  GEN_STRING(CUDA_ERROR_ILLEGAL_INSTRUCTION);
  GEN_STRING(CUDA_ERROR_MISALIGNED_ADDRESS);
  GEN_STRING(CUDA_ERROR_INVALID_ADDRESS_SPACE);
  GEN_STRING(CUDA_ERROR_INVALID_PC);
  GEN_STRING(CUDA_ERROR_LAUNCH_FAILED);
  GEN_STRING(CUDA_ERROR_COOPERATIVE_LAUNCH_TOO_LARGE);
  GEN_STRING(CUDA_ERROR_NOT_PERMITTED);
  GEN_STRING(CUDA_ERROR_NOT_SUPPORTED);
  GEN_STRING(CUDA_ERROR_SYSTEM_NOT_READY);
  GEN_STRING(CUDA_ERROR_SYSTEM_DRIVER_MISMATCH);
  GEN_STRING(CUDA_ERROR_COMPAT_NOT_SUPPORTED_ON_DEVICE);
  GEN_STRING(CUDA_ERROR_MPS_CONNECTION_FAILED);
  GEN_STRING(CUDA_ERROR_MPS_RPC_FAILURE);
  GEN_STRING(CUDA_ERROR_MPS_SERVER_NOT_READY);
  GEN_STRING(CUDA_ERROR_MPS_MAX_CLIENTS_REACHED);
  GEN_STRING(CUDA_ERROR_MPS_MAX_CONNECTIONS_REACHED);
  GEN_STRING(CUDA_ERROR_MPS_CLIENT_TERMINATED);
  GEN_STRING(CUDA_ERROR_STREAM_CAPTURE_UNSUPPORTED);
  GEN_STRING(CUDA_ERROR_STREAM_CAPTURE_INVALIDATED);
  GEN_STRING(CUDA_ERROR_STREAM_CAPTURE_MERGE);
  GEN_STRING(CUDA_ERROR_STREAM_CAPTURE_UNMATCHED);
  GEN_STRING(CUDA_ERROR_STREAM_CAPTURE_UNJOINED);
  GEN_STRING(CUDA_ERROR_STREAM_CAPTURE_ISOLATION);
  GEN_STRING(CUDA_ERROR_STREAM_CAPTURE_IMPLICIT);
  GEN_STRING(CUDA_ERROR_CAPTURED_EVENT);
  GEN_STRING(CUDA_ERROR_STREAM_CAPTURE_WRONG_THREAD);
  GEN_STRING(CUDA_ERROR_TIMEOUT);
  GEN_STRING(CUDA_ERROR_GRAPH_EXEC_UPDATE_FAILURE);
  GEN_STRING(CUDA_ERROR_EXTERNAL_DEVICE);
  GEN_STRING(CUDA_ERROR_INVALID_CLUSTER_SIZE);
  GEN_STRING(CUDA_ERROR_UNKNOWN);
  return 0;
}